"""Priority: `project`(take the higher)"""

ALARM_CLASS = 'tider.alarm.Alarm'
ALARM_MESSAGE_TYPE = 'text'  # markdown | text | html

BROKER_ACCEPT_CONTENT = ['json']
BROKER_BODY_ENCODING = None
BROKER_CONNECTION_MAX_RETRIES = 100
BROKER_CONNECTION_RETRY_ON_STARTUP = None
BROKER_CONNECTION_RETRY = True
BROKER_CONNECTION_TIMEOUT = 4
BROKER_DEFAULT_EXCHANGE = None
BROKER_DEFAULT_EXCHANGE_TYPE = 'direct'
BROKER_ENCODING = 'utf-8'
BROKER_FAILOVER_STRATEGY = None
BROKER_HEARTBEAT = 120
BROKER_HEARTBEAT_CHECKRATE = 3
BROKER_HOST = None
BROKER_LIMIT = 10000
BROKER_LOGIN_METHOD = None
BROKER_NO_ACK = False
BROKER_PASSWORD = None
BROKER_PORT = None
BROKER_QUEUES = ''
BROKER_TRANSPORT = None  # 'redis'
BROKER_TRANSPORT_OPTIONS = {}
BROKER_TRANSPORTS = {}
BROKER_URL = None
BROKER_USE_SSL = False
BROKER_USER = None
BROKER_VALIDATE_MESSAGE = True
BROKER_VHOST = None

CONCURRENCY = 1

CONTROL_QUEUE_TTL = 300.0
CONTROL_QUEUE_EXPIRES = 10.0
CONTROL_URL = None  # for heartbeat and control

CRAWLER_EXTENSIONS = {
    'filestore': 'tider.store.FilesStoreManager'
}

DEFAULT_USER_AGENT = None

DOWNLOADER_CONNECTION_POOL_BLOCK = False
DOWNLOADER_MAX_RETRIES = 0
DOWNLOADER_REMOVE_PROXY_ON_PROXY_ERROR = True
DOWNLOADER_WGET_DIR = '/'
DOWNLOADER_WGET_QUIET = True

DUPEFILTER_CLASS = None

EXPLORER = "tider.crawler.explorer.Explorer"
EXPLORER_API_CONCURRENCY = {}
EXPLORER_DOMAIN_CONCURRENCY = {}
EXPLORER_DOWNLOADERS = {}
EXPLORER_RETRY_PRIORITY_ADJUST = 1
EXPLORER_SESSION_AUTH = None
EXPLORER_SESSION_CERT = None
EXPLORER_SESSION_COOKIES = None
EXPLORER_SESSION_HEADERS = None
EXPLORER_SESSION_PROXIES = None
EXPLORER_SESSION_REDIRECT_LIMIT = 30
EXPLORER_SESSION_STREAM = False
EXPLORER_SESSION_TRUST_ENV = True
EXPLORER_SESSION_VERIFY = True
EXPLORER_USE_LOOP = False

FTP_USER = ""
FTP_PASSWORD = ""
FTP_USE_ACTIVE_MODE = False
FTP_URI = ""

FS_BASEDIR = ""

ITEM_PIPELINES = {}
ITEM_PROCESSOR = "tider.pipelines.ItemPipelineManager"

LOG_BACKUP_COUNT = 2
LOG_COLORIZE = True
LOG_DIRECTORY = '/'
LOG_ENCODING = "utf-8"
LOG_FILE = None
LOG_FORMAT = "%(asctime)s [%(process)d - %(threadName)s - %(name)s(line: %(lineno)d) - %(levelname)s] %(message)s"
LOG_HIJACK_ROOT = True
LOG_LEVEL = "INFO"
LOG_MAX_BYTES = 30 * 1024 * 1024
LOG_STDOUT = False
LOG_STDOUT_LEVEL = 'WARNING'

OSS_ACCESS_KEY_ID = ""
OSS_ACCESS_KEY_SECRET = ""
OSS_BUCKET_NAME = ""
OSS_DEFAULT_TIMEOUT = 50
OSS_DOMAIN = ""
OSS_ENDPOINT = ""

PARSER_ASYNC_START = True
PARSER_DEPTH_LIMIT = 0
PARSER_DEPTH_PRIORITY = 0
PARSER_USE_LOOP = False

# Never use this option to select the eventlet or gevent pool.
# You must use the -P option to tider crawler instead,
# to ensure the monkey patches aren’t applied too late,
# causing things to break in strange ways.
POOL = "threads"

PROXY_SCHEMAS = {}
PROXY_PARAMS = {}

SCHEDULER = "tider.crawler.scheduler.Scheduler"
SCHEDULER_MEMORY_QUEUE = "tider.pqueues.FifoMemoryQueue"
SCHEDULER_PRIORITY_QUEUE = "tider.pqueues:ExplorerAwarePriorityQueue"
SCHEDULER_BODY_PRIORITY_ADJUST = 0
SCHEDULER_DOWNSTREAM_QUEUE_MAXSIZE = 0

SPIDER_LOADER_CLASS = "tider.spiderloader.SpiderLoader"
SPIDER_LOADER_WARN_ONLY = False
SPIDER_MODULES = []
SPIDER_SCHEMAS = {}

STATS_CLASS = 'tider.statscollector.MemoryStatsCollector'
STATS_DUMP = True
STATSMAILER_RCPTS = []

STORE_SCHEMAS = {}
